* emacsadventures - my adventure of setting up Emacs
  :PROPERTIES:
  :CUSTOM_ID: emacsadventures
  :END:

#+BEGIN_SRC text
                                                                             __                                  __
                                                                            /  |                                /  |
  ______   _____  ____    ______    _______   _______         ______    ____$$ | __     __  ______   _______   _$$ |_    __    __   ______    ______    _______
 /      \ /     \/    \  /      \  /       | /       |       /      \  /    $$ |/  \   /  |/      \ /       \ / $$   |  /  |  /  | /      \  /      \  /       |
/$$$$$$  |$$$$$$ $$$$  | $$$$$$  |/$$$$$$$/ /$$$$$$$/        $$$$$$  |/$$$$$$$ |$$  \ /$$//$$$$$$  |$$$$$$$  |$$$$$$/   $$ |  $$ |/$$$$$$  |/$$$$$$  |/$$$$$$$/
$$    $$ |$$ | $$ | $$ | /    $$ |$$ |      $$      \        /    $$ |$$ |  $$ | $$  /$$/ $$    $$ |$$ |  $$ |  $$ | __ $$ |  $$ |$$ |  $$/ $$    $$ |$$      \
$$$$$$$$/ $$ | $$ | $$ |/$$$$$$$ |$$ \_____  $$$$$$  |      /$$$$$$$ |$$ \__$$ |  $$ $$/  $$$$$$$$/ $$ |  $$ |  $$ |/  |$$ \__$$ |$$ |      $$$$$$$$/  $$$$$$  |
$$       |$$ | $$ | $$ |$$    $$ |$$       |/     $$/       $$    $$ |$$    $$ |   $$$/   $$       |$$ |  $$ |  $$  $$/ $$    $$/ $$ |      $$       |/     $$/
 $$$$$$$/ $$/  $$/  $$/  $$$$$$$/  $$$$$$$/ $$$$$$$/         $$$$$$$/  $$$$$$$/     $/     $$$$$$$/ $$/   $$/    $$$$/   $$$$$$/  $$/        $$$$$$$/ $$$$$$$/

#+END_SRC

** Introduction
   :PROPERTIES:
   :CUSTOM_ID: introduction
   :END:

This is my adventure of setting up emacs for everyday use. I was
inspired by [[https://github.com/syl20bnr/spacemacs][Spacemacs]] and
[[https://github.com/myTerminal/super-emacs][super-emacs]]. My goals for
the configuration are

- Asthetic - an eye pleasing emacs
- Fast and productive
- emacsy - keep emacs behavior and add only when necessary, except now
  added EVIL mode

After I started learning Vim, I have switched to
[[https://github.com/emacs-evil/evil][EVIL mode]]. After this I (re)
discovered [[https://github.com/hlissner/doom-emacs][doom-emacs]] which
is almost on the same lines as my needs but is a much more advanced
emacs "distribution". I am currently evaluating the same for long term
usage.

A very similar config I found is
[[https://github.com/MatthewZMD/.emacs.d][M-EMACS]]

** [[file:screenshots/Screenshots.org][Screenshots]]
** How To Install
   :PROPERTIES:
   :CUSTOM_ID: how-to-install
   :END:

If you want to use my configuration, following are the steps

- Install [[https://github.com/adobe-fonts/source-code-pro/][Source Code
  Pro Fonts]]
- Clone this repository
- Link the resulting directory from your .emacs.d
- Add following line to your init.el
  =(load "~/.emacs.d/emacsadventures/loadMyConfig.el")=
- Start emacs
- look for any errors as some packages may fail to install
- Install the failed packages manually by running following
  =M-x packages-install-package=
- Install all-the-icons by running =M-x all-the-icons-install-fonts=
- On windows, you might need to install them from a resulting directory
- Restart emacs and begin your adventure

** How To Customize
   :PROPERTIES:
   :CUSTOM_ID: how-to-customize
   :END:

You can customize the configuration the usual emacs way.

- Start in the loadMyConfig.el
- comment out sections which you do not want
- Add yout personal configuration in the 'private' directory
- The personal configuration is loaded as a last step

** User Guide [Needs work]
   :PROPERTIES:
   :CUSTOM_ID: user-guide-needs-work
   :END:

[[/keybindings.md][Keybinding Quickref]] - This is loaded in every
session - search for buffer named "/emacsadventures-keyref/"

Please find the user guide at [[/userguide.md][User Guide]]

** Cheatsheets
   :PROPERTIES:
   :CUSTOM_ID: cheatsheets
   :END:

All the important cheatsheets are located in the [[/quickref][quickref]]
directory

- [[https://jblevins.org/projects/markdown-mode/][Markdown mode User
  Guide]]
- [[https://github.com/saf-dmitry/taskpaper-mode][Taskpaper mode User
  Guide]]

** Feedback
   :PROPERTIES:
   :CUSTOM_ID: feedback
   :END:

I would be very pleased if you give me feedback to improve this
configuration. I will try to improve as I go along using it. Thank You.

** TODOs
   :PROPERTIES:
   :CUSTOM_ID: todos
   :END:

-[ ] Move =setq= from =:config/:init= to =:custom= as is the
[[https://github.com/jwiegley/use-package#customizing-variables][suggestion]]
for use-package

** Tips and Tricks
If you are facing problems for vterm on M1 macs after update, following is a solution.
From - [[https://github.com/akermu/emacs-libvterm/issues/593#issuecomment-1754747095]]

#+BEGIN_SRC bash
$ cd ~/.config/emacs/.local/straight/build-29.1/vterm
$ rm -rf build
$ mkdir build
$ arch -arm64 cmake -B build
$ arch -arm64 cmake --build build

$ file vterm-module.so
vterm-module.so: Mach-O 64-bit bundle arm6
#+END_SRC

** Further Research
   :PROPERTIES:
   :CUSTOM_ID: further-research
   :END:

Furhter research for improvements

- +[[https://github.com/Alexander-Miller/treemacs][Replace Neotree with
  Treemacs]]+
- [[https://github.com/rakanalh/emacs-dashboard][emacs dashboard]]
- [[https://github.com/purcell/page-break-lines][page-break-lines]]
- [[https://github.com/alpaker/Fill-Column-Indicator][Fill-Column-Indicator]]
- [[https://github.com/saf-dmitry/taskpaper-mode][taskpaper-mode]]
- +[[https://github.com/casouri/nerdtab][buffer tabs - nerdtab]]+
- [[https://github.com/raxod502/straight.el][Experiment with Straight.el
  package manager]]

#  LocalWords:  emacsadventures
